fix docker tests by pinning older versions of Catch & slixmpp
- Catch: lab.louiz.org is down; use catchorg/Catch2, pin latest v1
- slixmpp: broke python 3.7 in v1.8 (cf below): pin 1.7 branch

slixmpp error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/slixmpp/types.py", line 16, in <module>
    from typing import (
ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)